#cloud-config
rancher:
write_files:
  - path: /home/rancher/init.sh
    permissions: "0755"
    owner: rancher
    content: |
      #!/bin/bash
      wait-for-docker
      sleep 60
      nslookup $(hostname).unil.ch | tail -1 | egrep -o [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ > /home/rancher/ip.conf
      nslookup $(hostname).mgmt.unil.ch | tail -1 | egrep -o [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ > /home/rancher/ip-mgmt.conf
      ip addr flush dev eth0
      ip addr flush dev eth1
      ip addr add $(cat /home/rancher/ip-mgmt.conf)/22 dev eth0
      ip addr add $(cat /home/rancher/ip.conf)/24 dev eth1
      ip route add default via 10.246.3.1

runcmd:
- [/home/rancher/init.sh]
