#cloud-config
runcmd:
  - echo "nslookup $(hostname).unil.ch | tail -1 | egreo -o [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" > /home/rancher/ip.conf
  - echo "nslookup $(hostname).mgmt.unil.ch | tail -1 | egreo -o [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" > /home/rancher/ip-mgmt.conf
